### ISSUE TITLE
Promote the use of comments, votes and starring of modules

### ISSUE THREAD

**Issue by dandv** [nodezoo/nodezoo-workshop#20]
I've filed this on [npmjs's repo](https://github.com/isaacs/npm-www/issues/298), without a response so far. Nodezoo seems headed more in the right direction.

Basically, as the number of modules trying to solve a specific task grows (try a [search for CSV](https://npmjs.org/search?q=csv)), it becomes more and more useful to have a mechanism of rating modules and leaving comments.

[CPAN](http://en.wikipedia.org/wiki/CPAN) has been doing a great job with 100k+ modules, and has been time-tested since 1997. Here's a screenshot of a [search for CSV](https://metacpan.org/search?q=csv)

![image](https://f.cloud.github.com/assets/33569/436606/1e67d7ba-b05d-11e2-8077-a81563ebec1a.png)

Modules can be rated, commented on, and favorited by logged in users.

**Comment by mcdonnelldean** [comment]
@dandv Agreed, sorry about the delay getting back but the idea is to light up such an experience.
