### ISSUE TITLE
SSH address verification issues

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#24]
The instructions in the readme give the command:
git clone git@github.com:[YOUR_USER]/nodezoo-web.git
Which can result in SSH key authentication issues.
Seeing as the clone-operation is read-only you only need the https address, so it should be:
git clone https://github.com/[YOUR_USER]/nodezoo-web.git

**Comment by mcdonnelldean** [comment]
@shanel262 Can you update these? Talk to @CodeWriterWriter If you need more info.

**Comment by shanel262** [comment]
@mcdonnelldean It's already fixed on master branch, do you want me to change it on the live one too?

**Comment by mcdonnelldean** [comment]
Oh, no, this is good.
