### ISSUE TITLE
NPM install instructions unclear

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#25]
The readme has the following instructions:
"In each branch, you always need to

$ npm install
to get the dependent Node.js modules."
Its unclear if this needs to be done during just the initial set up or after each change from i00, to i01 and so on.

**Comment by mcdonnelldean** [comment]
It needs to be initial and each branch, good spot

**Comment by CodeWriterWriter** [comment]
If it's on each branch change iteration.sh should be updated to include the "npm install" command for each repository. As it stands it currently just does the following for each repository:
"git checkout $ITER" where $ITER is the branch name

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter Can you clarify with @KristinaMatuleviciute what needs to be updated into the readme for this, it should be more clear.

**Comment by KristinaMatuleviciute** [comment]
done
