### ISSUE TITLE
Docker instructions unclear

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#26]
It should be more clearly stated in the readme where the instructions for the docker build and run commands are.
Also it should be explained somewhere in these instructions that in the command 
$ docker build -t TAG-NAME .
That the "." tells the terminal to use the DockerFile in the current working directory

**Comment by mcdonnelldean** [comment]
Docker bit to be redone in line with our changes to live so this will go away.
