### ISSUE TITLE
Nodezoo file structure issues

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#27]
Going through the readme it isn't immediately obvious that the other repositories should be at the same file hierarchy as the main nodezoo repository, as opposed to being sub folders within the main nodezoo.
As a consequence of this, attempting to run iterator.sh when the file structure is in any way different will cause the script to try to move to a folder that doesn't exist, and then use the command : 
git checkout $ITER
where ITER is the branch name. If ITER is blank, it defaults to i00, and changes the branch of the main Nodezoo to its i00, which doesn't have the iterator.sh script to allow you to switch back easily.

**Comment by mcdonnelldean** [comment]
I'll update the readme to be more specific here. Can you add the script as a PR to i00 so you can change back?

**Comment by CodeWriterWriter** [comment]
PR up for this
