### ISSUE TITLE
Iterator.sh set-up issues

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#28]
Before iterator.sh can be used the branch needs to be checked out and made a local branch for each repository using the commands:
git checkout upstream/[BRANCH NAME]
git checkout -b [BRANCH NAME]
This should be mentioned in the readme.

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter Assigning this to Kristina, can ye work together to add this section before the iteration sections?

**Comment by KristinaMatuleviciute** [comment]
done
