### ISSUE TITLE
Docker daemon unable to connect bug and fix

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#30]
Occasionaly when trying to build Docker files it'll not build and throw the message:
"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
The fix for this is to run the command: 
$ eval "$(docker-machine env default)"
immediately before building

**Comment by mcdonnelldean** [comment]
Will update docker instructions to match nodezoo-system where they are more explicit
