### ISSUE TITLE
Searches not functioning 

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#31]
Searches don't update in the browser, and change the url to be:
localhost:8000/?
the log of search event is as follows:
`2016-01-14T14:25:23.706Z ndj4goskoyfo/1452780787533/8010/search DEBUG	act	search       	IN	vrcsttjeuf3m/gneiv9at45zu	cmd:search,role:search	{role:search,cmd:search,query:request}	ENTRY	(ogg9h)	LISTEN	oozx0aoim26p/1452780919174/8267/web	-	`
`2016-01-14T14:25:23.753Z ndj4goskoyfo/1452780787533/8010/search DEBUG	act	search       	OUT	vrcsttjeuf3m/gneiv9at45zu	cmd:search,role:search	{items:[{name:request,version:2.67.0,giturl:git+https://github.com/request/request.git,desc:Simplified HTTP req	EXIT	(ogg9h)	LISTEN	oozx0aoim26p/1452780919174/8267/web	47`
Using the curl command to run the request does return a json object
Edit: This is the case for branches from i02 onward. Using the http api currently works

**Comment by mcdonnelldean** [comment]
This is because of elastic search, fixes will be remerged soon.
