### ISSUE TITLE
No explanation for grafana influx pairing

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#32]
The line in the read me is:
`You'll need to add your influxdb as data source and setup a dashboard.`
There's no further explanation and quality of online materials attempting to explain aren't satisfactory.

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter Good point, we will be replacing this with vidi but either way we should explain what we are doing here. Do you want to take a stab at this. Basically influx because it's easy to install and timeseries. Grafana because it works with influx and it's reasonably easy to use too.

**Comment by CodeWriterWriter** [comment]
PR up for this
