### ISSUE TITLE
Incorrect filename in readme

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#33]
In the readme for branches i03 onwards it says to run the command:
`node srv/npm-github.js --seneca.options.tag=npm --seneca.log.all --seneca.options.plugin.github.token=YOUR_GITHUB_TOKEN`
There is no npm-github.js file.
The file it means is github-dev.js in the nodezoo-github folder

**Comment by mcdonnelldean** [comment]
Will be fixed as part of readme update run through :D
