### ISSUE TITLE
Connection refused errors on http api

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-workshop#35]
On section i04 the http is giving connection refused errors, log here:
`{"code":"act_execute","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200,"eraro":true,"orig":{"code":"action-error","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200,"eraro":true,"orig":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200},"gate-executor":true,"package":"gate-executor","msg":"gate-executor: connect ECONNREFUSED 127.0.0.1:9200","details":{"id":"vsd30n40ut1g/k1fy6n6019fb","gate":false,"ungate":true,"desc":"cmd:search,role:search","plugin":{"name":"search","tag":"-"},"time":{"start":1452859127920,"end":1452859127922},"orig$":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9200},"message$":"connect ECONNREFUSED 127.0.0.1:9200"},"callpoint":"at Object.exports._errnoException (util.js:870:11)"},"gate-executor":true,"package":"seneca","msg":"seneca: Action cmd:search,role:search failed: connect ECONNREFUSED 127.0.0.1:9200.","details":{"id":"vsd30n40ut1g/k1fy6n6019fb","gate":false,"ungate":true,"desc":"cmd:search,role:search","plugin":{"name":"search","tag":"-"},"time":{"start":1452859127920,"end":1452859127922},"orig$":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":920`

**Comment by mcdonnelldean** [comment]
Checked this, looks like it was a rogue service, killall node works. Will update the readme with a note about it.
