### ISSUE TITLE
seneca-mesh cannot run on windows

### ISSUE THREAD

**Issue by BhaskaranR** [nodezoo/nodezoo-workshop#44]
Message: seneca: use-plugin: Could not load plugin mesh defined in seneca-mesh due to error: %1 is not a valid Win32 application.
\\?\C:\nodezooi05\nodezoo-info\node_modules\farmhash\build\Release\farmhash.node.

**Comment by mcdonnelldean** [comment]
@BhaskaranR Going to close this and instead open on Seneca mesh, I'll also update the readme to say this fact.
