### ISSUE TITLE
make github icons more consistent

### ISSUE THREAD

**Issue by dominictarr** [nodezoo/nodezoo-workshop#5]
It's highly useful to know if a module don't have a link to a github repo - so that I can immediately prune that module from my considerations.

but, sometimes the github icon doesn't appear, but the name still links to a git hub page,
example; 
hoarders in http://www.nodezoo.com/#q=grab-bag : name links to github, but no icon.
pomelo (in the same search) has no link at all.

I propose: github icon should always appear if there is a link.
if there is no way to get to github, show a sad face or something.

**Comment by mcdonnelldean** [comment]
On roadmap
