### ISSUE TITLE
is dependencies the best link for page-rank?

### ISSUE THREAD

**Issue by dominictarr** [nodezoo/nodezoo-workshop#8]
page-rank is a ranking via graph traversal, 
based on the model of a _random surfer_ http://en.wikipedia.org/wiki/PageRank 

Basically, the ranking the probability that you would visit that node if you started at a random node and randomly followed links. naturally, links with more in links are more easier to arrive at, and it's less likely to arrive at a particular node from a node that had many out links.

But I'm not sure that dependencies is quite the right graph to traverse, first of all, it's not really like the hyperlink graph of the web, it's not circular, and it's not gonna span the whole (or most of the) graph either.

What about, instead interpreting the the act of using a dependency as an expression of trust in the author(s) of that module? so, page-ranking authors instead of modules?

I feel that this reflects how I intuitively evaluate modules, what do you think?

**Comment by mcdonnelldean** [comment]
Has been removed but back on roadmap
